apiVersion: apps/v1
kind: Deployment
metadata:
  name: workers 
  labels: 
    application: communities
    function: workers 
    environment: staging
spec:
  selector:
    matchLabels:
      application: communities
      function: workers 
      environment: staging
  replicas: 2
  template: 
    metadata:
      name: communities-workers-pod-template
      labels:
        application: communities
        function: workers 
        environment: staging
        container: worker 
    spec:
      terminationGracePeriodSeconds: 600 
      volumes:
        - name: workspace
          emptyDir:
            sizeLimit: 200M
        - name: push-notification-secrets 
          secret:
            secretName: communities-push-notification-secrets
      containers:
        - name: workers-container
          image: 843012963492.dkr.ecr.us-east-1.amazonaws.com/communities/worker:0.6.0-rc5
          resources:
            requests:
              cpu: 200m
              memory: 200M
          volumeMounts:
            - mountPath: '/src/tmp'
              name: workspace
            - mountPath: '/src/security/'
              name: push-notification-secrets 
          env:
            ## Root Config values
            - name: NODE_ENV
              value: 'staging'
            - name: HOST
              value: 'https://staging.communities.social/'
            - name: WS_HOST
              value: 'wss://staging.communities.social/socket'
            - name: LOG_LEVEL
              value: 'debug'

            ## Database 
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: communities-database-credentials
                  key: host
                  optional: false
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: communities-database-credentials
                  key: port
                  optional: false
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: communities-database-credentials
                  key: username
                  optional: false
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: communities-database-credentials
                  key: password
                  optional: false

            ## Redis 
            - name: REDIS_HOST
              value: 'communities-staging-cache-redis-cluster.sh2hpr.0001.use1.cache.amazonaws.com'
            - name: REDIS_PORT
              value: '6379'

            ## Session
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: communities-session-secret
                  key: session_secret
                  optional: false

            ## S3
            - name: S3_BUCKET_URL
              value: 'https://communities-staging-storage.s3.amazonaws.com'
            - name: S3_BUCKET
              value: 'communities-staging-storage'
            - name: S3_ACCESS_ID
              valueFrom:
                secretKeyRef:
                  name: communities-s3-credentials
                  key: access_id
                  optional: false
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: communities-s3-credentials
                  key: access_key
                  optional: false

            ## Postmark
            - name: POSTMARK_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: communities-postmark-secrets
                  key: api_token 
                  optional: false

            ## Notifications
            - name: NOTIFICATIONS_IOS_PRIVATE_CERT_PATH
              value: '/security/apns-private.key.pem'
            - name: NOTIFICATIONS_IOS_PUBLIC_CERT_PATH
              value: '/security/apns-public.crt.pem'
            - name: NOTIFICATIONS_IOS_APPLICATION_BUNDLE_ID
              value: 'social.communities.staging'
            - name: NOTIFICATIONS_IOS_ENDPOINT
              value: 'https://api.sandbox.push.apple.com:443'
            - name: NOTIFICATIONS_FIREBASE_SERVICE_ACCOUNT_PATH
              value: '/security/firebase-service-account.json'

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: communities-workers 
  labels:
    application: communities
    function: workers
    environment: staging
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: workers 
  minReplicas: 2
  maxReplicas: 20 
  targetCPUUtilizationPercentage: 50
