apiVersion: apps/v1
kind: Deployment
metadata:
  name: communities-redis-deployment
  labels: 
    application: communities
    function: redis 
    environment: local
spec:
  selector:
    matchLabels:
      application: communities
      function: redis 
      environment: local
  replicas: 1
  template: 
    metadata:
      name: communities-redis-pod-template
      labels:
        application: communities
        function: redis 
        environment: local
        container: communities-redis
    spec:
      containers:
        - name: communities-redis-container
          image: redis
          ports:
            - containerPort: 6379 
          resources:
            limits:
              cpu: 200m 
              memory: 256M 
          imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: communities-redis
spec:
  selector:
    application: communities
    function: redis 
    environment: local
  ports:
    - protocol: TCP
      port: 6379 
      targetPort: 6379 



