apiVersion: apps/v1
kind: Deployment
metadata:
  name: communities-app-deployment
  labels:
    application: communities
    function: frontend-api
    environment: development
spec:
  selector:
    matchLabels:
      application: communities
      function: frontend-api
      environment: development
  replicas: 1
  template:
    metadata:
      name: communities-app-pod-template
      labels:
        application: communities
        function: frontend-api
        environment: development
        container: peerreview
    spec:
      containers:
        - name: communities-app-container
          image: communities:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 400m
            limits:
              cpu: 500m 
              memory: 512M 
          imagePullPolicy: Never
          env:
            - name: DEBUG
              value: "communities:*"
            - name: NODE_ENV
              value: development
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: communities-database-credentials
                  key: host
                  optional: false
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: communities-database-credentials
                  key: port
                  optional: false
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: communities-database-credentials
                  key: username
                  optional: false
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: communities-database-credentials
                  key: password
                  optional: false
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: communities-session-secret
                  key: session_secret
                  optional: false
            - name: S3_ACCESS_ID
              valueFrom:
                secretKeyRef:
                  name: communities-s3-credentials
                  key: access_id
                  optional: false
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: communities-s3-credentials
                  key: access_key
                  optional: false
            - name: ORCID_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: communities-orcid-secrets
                  key: client_id
                  optional: false
            - name: ORCID_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: communities-orcid-secrets
                  key: client_secret
                  optional: false
            - name: POSTMARK_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: communities-postmark-secrets
                  key: api_token 
                  optional: false

                 optional: false

---
apiVersion: v1
kind: Service
metadata:
  name: communities-app-service
spec:
  type: NodePort
  selector:
    application: communities
    function: frontend-api
    environment: development
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000



