apiVersion: apps/v1
kind: Deployment
metadata:
  name: workers 
  labels: 
    application: communities
    function: workers 
    environment: production
spec:
  selector:
    matchLabels:
      application: communities
      function: workers 
      environment: production
  replicas: 2
  template: 
    metadata:
      name: communities-workers-pod-template
      labels:
        application: communities
        function: workers 
        environment: production
        container: worker 
    spec:
      terminationGracePeriodSeconds: 600 
      containers:
        - name: workers-container
          image: 843012963492.dkr.ecr.us-east-1.amazonaws.com/communities/worker:0.1.1
          resources:
            requests:
              cpu: 200m
              memory: 200M
          env:
            - name: DEBUG
              value: "communities:*"
            - name: NODE_ENV
              value: production
            - name: HOST
              value: https://communities.social/
            - name: LOG_LEVEL
              value: info
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: communities-database-credentials
                  key: host
                  optional: false
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: communities-database-credentials
                  key: port
                  optional: false
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: communities-database-credentials
                  key: username
                  optional: false
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: communities-database-credentials
                  key: password
                  optional: false
            - name: REDIS_HOST
              value: communities-production-cache-redis-cluster.sh2hpr.0001.use1.cache.amazonaws.com
            - name: REDIS_PORT
              value: '6379'
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: communities-session-secret
                  key: session_secret
                  optional: false
            - name: S3_BUCKET_URL
              value: https://communities-production-storage.s3.amazonaws.com
            - name: S3_BUCKET
              value: communities-production-storage
            - name: S3_ACCESS_ID
              valueFrom:
                secretKeyRef:
                  name: communities-s3-credentials
                  key: access_id
                  optional: false
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: communities-s3-credentials
                  key: access_key
                  optional: false
            - name: POSTMARK_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: communities-postmark-secrets
                  key: api_token 
                  optional: false

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: communities-workers 
  labels:
    application: communities
    function: workers
    environment: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: workers 
  minReplicas: 2
  maxReplicas: 20 
  targetCPUUtilizationPercentage: 50
